import { LegalPage } from "@/components/LegalPage";

export const metadata = {
  title: "Disclaimer | GHC Academic Planner"
};

export default function DisclaimerPage() {
  return (
    <LegalPage
      eyebrow="Disclaimer"
      title="Disclaimer"
      intro="Please read this disclaimer before using GHC Academic Planner for course planning or graduation checks."
      officialLink
      sections={[
        {
          title: "Reference only",
          items: [
            "This website is provided for learning, planning, and general reference only.",
            "This website is not part of The University of Queensland and has no official partnership with The University of Queensland.",
            "Course information, graduation rules, prerequisites, semester availability, and planning suggestions may change."
          ]
        },
        {
          title: "Accuracy and responsibility",
          items: [
            "We try to keep data useful and accurate, but we do not guarantee that all information is always complete, current, or correct.",
            "Users must check the official UQ website and treat official UQ information as the final source of truth.",
            "GPA calculations, graduation checks, semester analysis, and course recommendations generated by this website are for reference only.",
            "Users are responsible for their own enrolment, course selection, and academic decisions."
          ]
        },
        {
          title: "Limitation of responsibility",
          items: [
            "This website is not responsible for any direct or indirect loss caused by using or relying on the website.",
            "If you are unsure about your degree plan, contact UQ Student Central, your faculty, or an official academic adviser."
          ]
        }
      ]}
    />
  );
}
